version: "2.2"

networks:
  proxy-tier:
    external:
      name: nginx-proxy

services:
  nginx: # 1.19
    restart: always
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/conf.d"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./volumes/proxy/certs:/etc/nginx/certs:ro"
    networks:
      - proxy-tier
  nginx-gen: #0.7.0
    restart: always
    image: jwilder/docker-gen
    container_name: nginx-gen
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./volumes/proxy/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
    volumes_from:
      - nginx
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -only-exposed -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

# latest as of script creation jrcs/letsencrypt-nginx-proxy-companion:2.0
  letsencrypt-nginx-proxy-companion:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./volumes/proxy/certs:/etc/nginx/certs:rw"
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen

  # letsencrypt-emergency:
  #   restart: always
  #   build: ./lets-encrypt-emergency/
  #   container_name: letsencrypt-emergency
  #   volumes_from:
  #     - nginx
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock:ro"
  #     - "./volumes/proxy/certs:/etc/nginx/certs:rw"
  #   environment:
  #     - NGINX_DOCKER_GEN_CONTAINER=nginx-gen



# websites configured section ---------------

  # gitea personal gitforge -- git.jrtechs.net
  # gitea directory is at same level as infrastructure directory.
  # api port 3000 is used on localhost to sync gitea with github /jrtechs
  gitea:
    image: gitea/gitea:1.13.0
    container_name: gitea
    restart: always
    networks:
      - proxy-tier
    volumes:
      - ./gitea/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - VIRTUAL_HOST=git.jrtechs.net
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=git.jrtechs.net
      - LETSENCRYPT_EMAIL=jeffery@jrtechs.net

  video:
    image: home-brew-plex
    build: ./HomeBrewPlex/
    container_name: home-brew-plex
    restart: always
    networks:
      - proxy-tier
    volumes:
      - ./HomeBrewPlex/:/src
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "4000:4000"
      - "4444:4444"
    environment:
      - VIRTUAL_HOST=video.jrtechs.net
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=4000
      - LETSENCRYPT_HOST=video.jrtechs.net
      - LETSENCRYPT_EMAIL=admin@jrtechs.net


# portfolio website
  test-portfolio-website:
    restart: always
    image: portfolio-website
    build: ./Portfolio_Website
    container_name: test-portfolio-website
    networks:
      - proxy-tier
    volumes:
      - "./volumes/proxy/jrtechs.me/:/etc/nginx/conf.d"
    ports:
      - 6666:6666
    environment:
      - VIRTUAL_HOST=test.jrtechs.me
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=6666
      - LETSENCRYPT_HOST=test.jrtechs.me
      - LETSENCRYPT_EMAIL=jeffery@jrtechs.net
