version: "2.2"

networks:
  proxy-tier:
    external:
      name: nginx-proxy

services:

  # gitea personal gitforge -- git.jrtechs.net
  # gitea directory is at same level as infrastructure directory.
  # api port 3000 is used on localhost to sync gitea with github /jrtechs
  gitea:
    image: gitea/gitea:1.13.0
    container_name: gitea
    restart: always
    networks:
      - proxy-tier
    volumes:
      - ./gitea/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
    environment:
      - USER_UID=1000
      - USER_GID=1000


  #video.jrtechs.net
  video:
    image: home-brew-plex
    build: ./HomeBrewPlex/
    container_name: home-brew-plex
    restart: always
    networks:
      - proxy-tier
    volumes:
      - ./HomeBrewPlex/:/src
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "4000:4000"


  # portfolio website
  # jrtechs.me
  portfolio-website:
    restart: always
    image: portfolio-website
    build: ./Portfolio_Website
    container_name: portfolio-website
    networks:
      - proxy-tier
    volumes:
      - "./volumes/proxy/jrtechs.me/:/etc/nginx/conf.d"
    ports:
      - "6666:6666"

  # jrtechs.net
  # personal blog
  blogdb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    # environment:
    #   MYSQL_ROOT_PASSWORD: password
    env_file:
      - sql.env
    volumes:
      - "./NodeJSBlog/db:/var/lib/mysql"
    networks:
      - proxy-tier
  jrtechs-blog:
    image: nodejsblog
    build: ./NodeJSBlog
    container_name: jrtechs-blog
    volumes:
      - ./NodeJSBlog:/src
    restart: always
    links:
      - blogdb:database
    networks:
      - proxy-tier
    depends_on:
      - blogdb
    ports:
      - "8000:8000"

  # github graphs
  # github-graphs.com
  live-github-graphs:
    image: github-graphs
    build: ./github-graphs/
    container_name: node-github-graphs
    restart: always
    networks:
      - proxy-tier
    volumes:
      - ./github-graphs/:/src
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "7000:7000"


  # club panda
  # clubpanda.jrtechs.net
  clubdb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - sql.env
    volumes:
      - "./Club-Panda/db:/var/lib/mysql"
    networks:
      - proxy-tier
  php:
    build: ./Club-Panda/php_docker/
    restart: always
    networks:
      - proxy-tier
    volumes:
      - ./Club-Panda:/app/public
    links:
      - clubdb
  club-panda-games:
    build: ./Club-Panda/
    restart: always
    volumes:
      - ./Club-Panda:/app/public
    links:
      - php
      - clubdb
    depends_on:
      - php
      - clubdb
    networks:
      - proxy-tier
    ports:
      - "8888:80"
